const coursesData = [
  {
    id: 1,
    name: 'Illustration',
    bgColor: '#f7bac4',
    quantity: '12',
    isNew: false,
    isFavorite: true,
    views: '1201',
  },
  {
    id: 2,
    name: 'Graphic design',
    bgColor: '#d1e8be',
    quantity: '12',
    isNew: false,
    isFavorite: false,
    views: '1202',
  },
  {
    id: 3,
    name: 'adobe photoshop',
    bgColor: '#89d0ef',
    quantity: '12',
    isNew: false,
    isFavorite: false,
    views: '1203',
  },
  {
    id: 4,
    name: 'Programming base',
    bgColor: '#eed6ca',
    quantity: '12',
    isNew: false,
    isFavorite: false,
    views: '1204',
  },
  {
    id: 5,
    name: 'FrontEnd development',
    bgColor: '#fccd68',
    quantity: '12',
    isNew: false,
    isFavorite: true,
    views: '1205',
  },
  {
    id: 6,
    name: 'BackEnd development',
    bgColor: '#fe95b4',
    quantity: '12',
    isNew: false,
    isFavorite: true,
    views: '1206',
  },
  {
    id: 7,
    name: 'Swift',
    bgColor: '#c8edcf',
    quantity: '12',
    isNew: false,
    isFavorite: false,
    views: '1207',
  },
  {
    id: 8,
    name: 'Python',
    bgColor: '#f7bfc1',
    quantity: '12',
    isNew: false,
    isFavorite: false,
    views: '1208',
  },
  {
    id: 9,
    name: 'React',
    bgColor:  '#a0c09f',
    quantity: '12',
    isNew: true,
    isFavorite: false,
    views: '1209',
  },
  {
    id: 10,
    name: 'Vue.js',
    bgColor: '#dec5ef',
    quantity: '12',
    isNew: false,
    isFavorite: false,
    views: '1210',
  }, 
];

export default coursesData;
